name: AdminFaces Showcase continuous integration

on: [push, pull_request]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8.0.212
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: ChromeDriver Script
        run: |
          CHROME_VERSION=80.0.3987.106
          # Download and unpack latest release of chromedriver
          echo "Downloading chromedriver v$CHROME_VERSION..."
          wget "https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          rm chromedriver_linux64.zip
          CHROMEDRIVER_DIR="/usr/local/share/chrome_driver"
          CHROMEDRIVER_BIN="$CHROMEDRIVER_DIR/chromedriver"
          sudo rm -rf $CHROMEDRIVER_DIR/*
          sudo rm -rf $CHROMEDRIVER_BIN/*
          sudo mkdir -p $CHROMEDRIVER_DIR
          sudo mv "chromedriver" $CHROMEDRIVER_BIN
          sudo chmod +x $CHROMEDRIVER_BIN
          chromedriver --version
      - name: Maven Package
        run: mvn clean package -DskipTests
      - name: Wildfly-8
        run: mvn test -Ptests -Pwildfly8-managed -Dbrowser=chromeheadless -Dwebdriver.chrome.driver=/usr/local/share/chrome_driver
      - name: Glassfish-5
        run: mvn test -Ptests -Pwildfly8-managed -Dbrowser=chromeheadless
      - name: Tomee-7
        run: mvn test -Ptests -Ptomee7-remote -Dbrowser=chromeheadless
      - name: Tomee-1.7
        run: mvn test -Ptests -Ptomee1.7-remote -Dbrowser=chromeheadless



